Don't create reviewday subdirectory
Perhaps because of the new resource ordering algorithm, on puppet 4 the
/var/lib/reviewday/reviewday file resource blocks the
/var/lib/reviewday/reviewday vcsrepo resource and results in failures
like:

 Error: /Stage[main]/Main/Reviewday::Site[reviewday]/Vcsrepo[/var/lib/reviewday/reviewday]/ensure: change from absent to latest failed: Could not create repository (non-repository at path)

On both puppet 3 and puppet 4 the vcsrepo resource will create the
directory on its own, and it can also manage the directory's owner and
group itself, so there is no need for it to be managed independently.

Change-Id: Ic64d39a9f257d623ca13e9d38708eaa1e32e8c18